#!/usr/bin/env bash
export MOZ_ENABLE_WAYLAND=1
export GDK_BACKEND=wayland
export SDL_VIDEODRIVER=wayland
export $(dbus-launch)
.bin/startDesktopPortal &
exec /usr/libexec/polkit-gnome-authentication-agent-1 &
exec gentoo-pipewire-launcher &
exec gentoo-pipewire-launcher restart &
exec foot -s &
exec wbg /home/thiago/Pictures/wallpaper.png &

